version: '3.1'

services:

  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - espocrm-network

  espocrm-nginx:
    image: nginx
    container_name: espocrm-nginx
    env_file: .env
    environment:
      NGINX_HOST: "${DOMAIN_NAME}"
    volumes:
      - ./data/nginx/conf.d/:/etc/nginx/templates
      - espocrm:/var/www/html
      - ./data/nginx/espocrm.conf:/etc/nginx/espocrm.conf
      - ./data/nginx/logs:/var/log/nginx
    restart: always
    depends_on:
      - espocrm
      - espocrm-websocket
    ports:
      - "80:80"
    networks:
      - espocrm-network

  espocrm:
    container_name: espocrm
    image: "${ESPOCRM_IMAGE}"
    env_file: .env
    environment:
      ESPOCRM_DATABASE_NAME: "${DATABASE_NAME}"
      ESPOCRM_DATABASE_HOST: mysql
      ESPOCRM_DATABASE_USER: "${DATABASE_USER}"
      ESPOCRM_DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      ESPOCRM_ADMIN_USERNAME: "${ESPOCRM_ADMIN_USERNAME}"
      ESPOCRM_ADMIN_PASSWORD: "${ESPOCRM_ADMIN_PASSWORD}"
      ESPOCRM_SITE_URL: "${ESPOCRM_SITE_URL}"
    restart: always
    volumes:
     - espocrm:/var/www/html
    depends_on:
      - mysql
    networks:
      - espocrm-network

  espocrm-daemon:
    container_name: espocrm-daemon
    image: "${ESPOCRM_DAEMON_IMAGE}"
    volumes:
     - espocrm:/var/www/html
    restart: always
    depends_on:
      - espocrm
    entrypoint: docker-daemon.sh
    networks:
      - espocrm-network

  espocrm-websocket:
    container_name: espocrm-websocket
    image: "${ESPOCRM_WEBSOCKET_IMAGE}"
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
     - espocrm:/var/www/html
    restart: always
    depends_on:
      - espocrm
    entrypoint: docker-websocket.sh
    ports:
      - "8080:8080"
    networks:
      - espocrm-network

networks:
  espocrm-network:
    driver: bridge

volumes:
  mysql:
  espocrm: